version: '3.3'

services:
  frontend:
    build: ./frontend
    container_name: crypto_frontend
    ports:
      - "3000:80"
    networks:
      - crypto_labwork
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: crypto_backend
    ports:
      - "8000:8000"
    networks:
      - crypto_labwork

networks:
  crypto_labwork:
    driver: bridge